[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  GENERATE_SOURCEMAP = "false"

[dev]
  command = "npm run start:frontend"
  port = 8888
  targetPort = 3001
  publish = "build"
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
