import { QuizQuestion } from "./MazeQuiz";

// ---------- Quiz helpers ----------
export const SAMPLE_QUIZ: QuizQuestion[] = [
  {
    id: "1",
    question: "What does CPU stand for?",
    correct: "Central Processing Unit",
    false1: "Computer Primary Utility",
    false2: "Control Program Unit",
    false3: "Central Peripheral Unit",
  },
  {
    id: "2",
    question: "Which number system is base-2?",
    correct: "Binary",
    false1: "Decimal",
    false2: "Hexadecimal",
    false3: "Octal",
  },
  {
    id: "3",
    question: "What does RAM provide for a computer?",
    correct: "Temporary working memory",
    false1: "Permanent storage",
    false2: "Graphics rendering",
    false3: "Network connectivity",
  },
  {
    id: "4",
    question: "Which algorithm has average O(n log n) time?",
    correct: "Merge sort",
    false1: "Bubble sort",
    false2: "Linear search",
    false3: "Selection sort",
  },
  {
    id: "5",
    question: "What is the purpose of an if-statement?",
    correct: "Make a decision based on a condition",
    false1: "Repeat code a fixed number of times",
    false2: "Store multiple values",
    false3: "Convert data types",
  },
  {
    id: "6",
    question: "Which data structure uses FIFO order?",
    correct: "Queue",
    false1: "Stack",
    false2: "Tree",
    false3: "Hash map",
  },
  {
    id: "7",
    question: "Which Boolean operator returns true only if both inputs are true?",
    correct: "AND",
    false1: "OR",
    false2: "XOR",
    false3: "NOT",
  },
  {
    id: "8",
    question: "What does HTML stand for?",
    correct: "HyperText Markup Language",
    false1: "High Tech Machine Language",
    false2: "Hyperlink Transfer Method",
    false3: "Home Tool Markup List",
  },
  {
    id: "9",
    question: "Which device stores data even when powered off?",
    correct: "SSD",
    false1: "RAM",
    false2: "Cache",
    false3: "Register",
  },
  {
    id: "10",
    question: "Which protocol secures HTTP traffic?",
    correct: "TLS",
    false1: "FTP",
    false2: "SMTP",
    false3: "UDP",
  },
  {
    id: "11",
    question: "What is a variable in programming?",
    correct: "A named storage location for data",
    false1: "An always-true condition",
    false2: "A compiler directive",
    false3: "A random number generator",
  },
  {
    id: "12",
    question: "Which loop continues while a condition is true?",
    correct: "while loop",
    false1: "for-each loop always once",
    false2: "do-nothing loop",
    false3: "until-never loop",
  },
  {
    id: "13",
    question: "What does ‘OOP’ stand for?",
    correct: "Object-Oriented Programming",
    false1: "Open Operating Process",
    false2: "Optimal Output Protocol",
    false3: "Ordered Object Pooling",
  },
  {
    id: "14",
    question: "Which keyword typically defines a reusable block of code?",
    correct: "function",
    false1: "return",
    false2: "break",
    false3: "case",
  },
  {
    id: "15",
    question: "What is recursion?",
    correct: "A function calling itself",
    false1: "A loop with a counter",
    false2: "A random shuffle",
    false3: "An error that crashes code",
  },
  {
    id: "16",
    question: "Which file extension is most likely a plain text source code file?",
    correct: ".py",
    false1: ".jpg",
    false2: ".mp3",
    false3: ".exe",
  },
  {
    id: "17",
    question: "Which is a benefit of using functions?",
    correct: "Code reuse and organization",
    false1: "Slower execution",
    false2: "More syntax errors guaranteed",
    false3: "Removes need for testing",
  },
  {
    id: "18",
    question: "Which statement about arrays is true?",
    correct: "They store elements in contiguous memory",
    false1: "They always grow automatically",
    false2: "They store key-value pairs by default",
    false3: "They are unordered by design",
  },
  {
    id: "19",
    question: "What does a compiler do?",
    correct: "Translates source code to machine code",
    false1: "Executes machine code directly",
    false2: "Manages hardware power states",
    false3: "Sends packets across networks",
  },
  {
    id: "20",
    question: "Which practice improves cybersecurity?",
    correct: "Using strong unique passwords",
    false1: "Sharing logins for convenience",
    false2: "Clicking unknown links",
    false3: "Disabling updates permanently",
  },
];