interface WordsByLength {
  [key: string]: string[];
}

// export const words: WordsByLength = {

//   "3": [
//     "study",
//     "time",
//     "test",
//     "day",
//     // "school",
//     // "supplies",
//     // "sharp",
//     // "pencil",
//     // "open",
//     // "book",
//     // "final",
//     // "exam",
//     // "brain",
//     // "power",
//     // "class",
//     // "project",
//     // "learning",
//     // "curve",
//     // "teachers",
//     // "desk",
//   ],
// };
export const words: WordsByLength = {
  "2": ["up", "in"],
  "3": [
    "hug",
    "joy",
    "hug",
    "ear",
    "you",
    "hug",
    "act",
    "hug",
    "usb",
    "api",
    "web",
    "gpu",
    "bit",
    "cpu",
    "app",
    "log",
    "tag",
    "css",
    "dns",
    "sql",
    "git",
    "log",
    "dev",
    "ssl",
    "cli",
    "dev",
    "api",
    "npm",
    "big",
    "win",
    "win",
    "job",
    "run",
    "bar",
    "job",
    "top",
    "key",
    "win",
    "win",
    "big",
    "win",
    "win",
    "big",
    "new",
    "new",
    "met",
    "hit",
    "fix",
    "top",
    "win",
    "aim",
    "day",
    "lab",
    "pop",
    "lab",
    "pen",
    "ink",
    "aid",
    "due",
    "log",
    "lab",
    "pad",
    "aid",
    "pet",
    "app",
    "bus",
    "lab",
    // "ant",
    // "bat",
    // "the",
    // "cat",
    // "dog",
    // "egg",
    // "fan",
    // "gum",
    // "hat",
    // "ice",
    // "jam",
    // "kid",
    // "log",
    // "man",
    // "net",
    // "map",
    // "owl",
    // "pen",
    // "rat",
    // "sun",
    // "tap",
    // "urn",
    // "van",
    // "web",
    // "yak",
    // "zip",
    // "bag",
    // "cap",
    // "den",
    // "ear",
    // "fig",
    // "gap",
    // "mid",
    // "hop",
    // "ink",
    // "jet",
    // "sus",
    // "kit",
    // "lid",
    // "nap",
    // "oak",
    // "pit",
    // "rib",
    // "sip",
    // "top",
    // "urn",
    // "vet",
    // "win",
    // "xen",
    // "yam",
    // "zen",
    // "ace",
    // "bee",
    // "cub",
    // "joy",
    // "fun",
    // "yes",
    // "win",
    // "sun",
    // "gem",
    // "hug",
    // "dip",
    // "elf",
    // "fin",
    // "got",
    // "hen",
    // "job",
    // "key",
    // "low",
    // "mix",
    // "nod",
    // "off",
    // "pop",
    // "ran",
    // "tin",
    // "use",
    // "vow",
    // "box",
    // "dot",
    // "eat",
    // "fix",
    // "gym",
    // "hug",
    // "ion",
    // "jar",
    // "kin",
    // "lay",
    // "mom",
    // "net",
    // "old",
    // "ask",
    // "aid",
    // "win",
    // "try",
    // "net",
    // "tip",
    // "joy",
    // "pad",
    // "run",
    // "tag",
    // "try",
    // "upn",
    // "wet",
    // "yep",
    // "zip",
    // "ark",
    // "bud",
    // "cow",
    // "app",
    // "cpu",
    // "ram",
    // "api",
    // "pay",
    // "win",
    // "net",
    // "tip",
    // "bag",
    // "job",
    // "gem",
    // "gui",
    // "usb",
    // "web",
    // "vpn",
    // "mac",
    // "ssd",
    // "dig",
    // "end",
    // "was",
    // "cap",
    // "who",
  ],
  "4": [
    "help",
    "hand",
    "warm",
    "soft",
    "open",
    "arms",
    "eyes",
    "kind",
    "true",
    "talk",
    "safe",
    "calm",
    "soul",
    "wave",
    "deep",
    "love",
    "ally",
    "fair",
    "play",
    "grin",
    "good",
    "gift",
    "nice",
    "word",
    "kept",
    "bond",
    "made",
    "soft",
    "true",
    "warm",
    "word",
    "eyes",
    "wave",
    "hand",
    "open",
    "pure",
    "bond",
    "beam",
    "eyes",
    "safe",
    "open",
    "door",
    "care",
    "bond",
    "zone",
    "hand",
    "kind",
    "true",
    "good",
    "love",
    "made",
    "open",
    "ears",
    "grin",
    "help",
    "code",
    "data",
    "wifi",
    "port",
    "call",
    "node",
    "gate",
    "tool",
    "page",
    "code",
    "boot",
    "rate",
    "ping",
    "test",
    "core",
    "disk",
    "miss",
    "tech",
    "name",
    "loop",
    "file",
    "path",
    "loop",
    "byte",
    "html",
    "grid",
    "sync",
    "code",
    "base",
    "loss",
    "code",
    "test",
    "case",
    "leak",
    "port",
    "spam",
    "repo",
    "tool",
    "form",
    "loop",
    "form",
    "rule",
    "cert",
    "hash",
    "call",
    "user",
    "auth",
    "push",
    "dark",
    "mode",
    "code",
    "copy",
    "tool",
    "mode",
    "node",
    "auth",
    "code",
    "boot",
    "site",
    "goal",
    "plan",
    "move",
    "bold",
    "step",
    "hard",
    "work",
    "mind",
    "good",
    "next",
    "firm",
    "will",
    "goal",
    "path",
    "long",
    "high",
    "task",
    "done",
    "well",
    "grit",
    "earn",
    "deep",
    "plan",
    "true",
    "grit",
    "form",
    "goal",
    "mind",
    "step",
    "long",
    "haul",
    "work",
    "firm",
    "goal",
    "mode",
    "team",
    "bold",
    "keep",
    "push",
    "turn",
    "move",
    "idea",
    "deep",
    "dive",
    "call",
    "push",
    "team",
    "move",
    "plan",
    "next",
    "step",
    "risk",
    "role",
    "pace",
    "goal",
    "plan",
    "made",
    "wise",
    "move",
    "path",
    "calm",
    "mind",
    "bold",
    "gain",
    "step",
    "goal",
    "list",
    "hope",
    "held",
    "mark",
    "peak",
    "form",
    "game",
    "face",
    "goal",
    "fast",
    "lane",
    "lead",
    "role",
    "goal",
    "task",
    "beat",
    "paid",
    "true",
    "test",
    "quiz",
    "case",
    "note",
    "card",
    "desk",
    "open",
    "book",
    "mind",
    "exam",
    "coat",
    "book",
    "math",
    "test",
    "quiz",
    "prep",
    "bell",
    "hour",
    "trip",
    "plan",
    "text",
    "book",
    "quiz",
    "time",
    "help",
    "home",
    "work",
    "note",
    "book",
    "math",
    "quiz",
    "test",
    "word",
    "list",
    "fair",
    "quiz",
    "test",
    "prep",
    "open",
    "roll",
    "desk",
    "dust",
    "zone",
    "desk",
    "help",
    "term",
    "lamp",
    "quiz",
    "note",
    "math",
    "play",
    "tool",
    "exam",
    "peer",
    "bell",
    "ring",
    "exam",
    "hall",
    "test",
    "quiz",
    "test",
    "help",
    "exam",
    "read",
    "goal",
    "edge",
    "slip",
    "trip",
    "pass",
    "quiz",
    "home",
    "pass",
    "work",
    "exam",
    "desk",
    "note",
    // "bird",
    // "cake",
    // "what",
    // "when",
    // "code",
    // "drip",
    // "data",
    // "html",
    // "java",
    // "gold",
    // "cash",
    // "king",
    // "coin",
    // "save",
    // "earn",
    // "rich",
    // "fund",
    // "deal",
    // "sale",
    // "gain",
    // "byte",
    // "bash",
    // "node",
    // "disk",
    // "file",
    // "ping",
    // "duck",
    // "fish",
    // "goat",
    // "hand",
    // "jump",
    // "kite",
    // "lamp",
    // "moon",
    // "nest",
    // "open",
    // "play",
    // "rain",
    // "ship",
    // "tree",
    // "kind",
    // "good",
    // "love",
    // "hope",
    // "nice",
    // "fair",
    // "hero",
    // "glad",
    // "calm",
    // "free",
    // "unit",
    // "vent",
    // "wind",
    // "xray",
    // "yarn",
    // "zinc",
    // "ball",
    // "cold",
    // "drum",
    // "ever",
    // "frog",
    // "girl",
    // "hill",
    // "iron",
    // "joke",
    // "lava",
    // "mice",
    // "name",
    // "oven",
    // "peck",
    // "quiz",
    // "rock",
    // "sand",
    // "toes",
    // "urge",
    // "view",
    // "wolf",
    // "yard",
    // "zoom",
    // "ally",
    // "bake",
    // "calm",
    // "dive",
    // "echo",
    // "farm",
    // "game",
    // "heat",
    // "idea",
    // "jade",
    // "keep",
    // "leaf",
    // "mint",
    // "love",
    // "help",
    // "care",
    // "give",
    // "kind",
    // "calm",
    // "soft",
    // "safe",
    // "true",
    // "dear",
    // "note",
    // "oval",
    // "pack",
    // "race",
    // "seat",
    // "tide",
    // "vast",
    // "wave",
    // "xmas",
    // "zero",
    // "arch",
    // "belt",
    // "clay",
    // "deer",
    // "each",
    // "face",
    // "gift",
    // "hard",
    // "inch",
    // "join",
    // "loud",
    // "melt",
    // "neck",
    // "ogle",
    // "pine",
    // "rope",
    // "song",
    // "tent",
    // "unit",
    // "vase",
    // "walk",
    // "yoga",
    // "zone",
    // "aqua",
    // "blue",
    // "cool",
    // "door",
    // "kind",
    // "help",
    // "kind",
    // "give",
    // "earn",
    // "self",
    // "grow",
    // "gain",
    // "idea",
    // "plan",
    // "wise",
    // "calm",
  ],
  "5": [
    // "apple",
    // "bunny",
    // "chair",
    // "learn",
    // "slaps",
    // "think",
    // "solve",
    // "heart",
    // "peace",
    // "share",
    // "sweet",
    // "trust",
    // "grace",
    // "angel",
    // "touch",
    // "grass",
    // "smile",
    // "human",
    // "unity",
    // "brave",
    // "share",
    // "trust",
    // "skill",
    // "grasp",
    // "value",
    // "asset",
    // "bonus",
    // "worth",
    // "stock",
    // "prize",
    // "raise",
    // "trade",
    // "bucks",
    // "trust",
    // "value",
    // "focus",
    // "dance",
    // "eagle",
    // "flame",
    // "happy",
    // "smile",
    // "peace",
    // "trust",
    // "brave",
    // "shine",
    // "input",
    // "array",
    // "block",
    // "cloud",
    // "mouse",
    // "drive",
    // "email",
    // "logic",
    // "fetch",
    // "proxy",
    // "cheer",
    // "sweet",
    // "thank",
    // "charm",
    // "grape",
    // "house",
    // "igloo",
    // "jelly",
    // "koala",
    // "lemon",
    // "magic",
    // "nurse",
    // "ocean",
    // "piano",
    // "queen",
    // "robot",
    // "smile",
    // "tiger",
    // "uncle",
    // "vivid",
    // "whale",
    // "xylos",
    // "yacht",
    // "zebra",
    // "angle",
    // "baker",
    // "candy",
    // "daisy",
    // "eager",
    // "fairy",
    // "giant",
    // "happy",
    // "index",
    // "jolly",
    // "kneel",
    // "laugh",
    // "match",
    // "orbit",
    // "plant",
    // "quiet",
    // "rainy",
    // "shine",
    // "train",
    // "under",
    // "vocal",
    // "wrist",
    // "yummy",
    // "zippy",
    // "acorn",
    // "brave",
    // "clean",
    // "dream",
    // "earth",
    // "field",
    // "glide",
    // "heart",
    // "inbox",
    // "jumps",
    // "liver",
    // "merry",
    // "noble",
    // "organ",
    // "pouch",
    // "quack",
    // "rider",
    // "smart",
    // "ultra",
    // "voice",
    // "world",
    // "xenon",
    // "youth",
    // "azure",
    // "beach",
    // "cloud",
    // "drill",
    // "enter",
    // "flock",
    // "grill",
    // "honey",
    // "input",
    // "jewel",
    // "karma",
    // "lemon",
    // "mango",
    // "night",
    // "oasis",
    // "penny",
    // "quick",
    // "river",
    // "swing",
    // "trick",
    // "unity",
    // "vapor",
    // "witty",
    // "zonal",
    // "power",
    // "eagle",
    "heart",
    "smile",
    "touch",
    "peace",
    "space",
    "sweet",
    "words",
    "voice",
    "trust",
    "brave",
    "cheer",
    "given",
    "shown",
    "heart",
    "laugh",
    "grace",
    "faith",
    "sweet",
    "heart",
    "smile",
    "thank",
    "given",
    "light",
    "touch",
    "heart",
    "loyal",
    "peace",
    "quiet",
    "happy",
    "tears",
    "laugh",
    "moral",
    "space",
    "given",
    "vibes",
    "group",
    "peace",
    "smile",
    "words",
    "given",
    "stack",
    "cloud",
    "logic",
    "debug",
    "smart",
    "drive",
    "error",
    "space",
    "cache",
    "stack",
    "error",
    "logic",
    "error",
    "patch",
    "boost",
    "stack",
    "trace",
    "query",
    "build",
    "error",
    "debug",
    "query",
    "input",
    "mouse",
    "click",
    "email",
    "error",
    "merge",
    "route",
    "width",
    "media",
    "query",
    "image",
    "table",
    "login",
    "error",
    "shell",
    "build",
    "query",
    "param",
    "react",
    "redux",
    "store",
    "token",
    "clear",
    "daily",
    "grind",
    "small",
    "smart",
    "habit",
    "level",
    "sharp",
    "dream",
    "clear",
    "shown",
    "value",
    "added",
    "trust",
    "focus",
    "solid",
    "sharp",
    "shown",
    "major",
    "level",
    "great",
    "pitch",
    "ethic",
    "lucky",
    "break",
    "clean",
    "board",
    "grind",
    "climb",
    "quick",
    "daily",
    "going",
    "sharp",
    "right",
    "skill",
    "value",
    "worth",
    "fight",
    "right",
    "final",
    "smart",
    "quick",
    "pivot",
    "clear",
    "quick",
    "adapt",
    "major",
    "shift",
    "level",
    "dream",
    "reach",
    "small",
    "climb",
    "chain",
    "study",
    "guide",
    "score",
    "sharp",
    "final",
    "class",
    "rules",
    "group",
    "lunch",
    "break",
    "chalk",
    "board",
    "grade",
    "level",
    "study",
    "field",
    "white",
    "board",
    "paper",
    "class",
    "stack",
    "grade",
    "notes",
    "pride",
    "honor",
    "chair",
    "guide",
    "brain",
    "storm",
    "chalk",
    "sheet",
    "field",
    "notes",
    "tutor",
    "paper",
    "board",
    "notes",
    "extra",
    "study",
    "final",
    "grade",
    "study",
    "break",
    "daily",
    "grade",
    "scale",
    "study",
    "class",
    "extra",
    "group",
    "study",
    "score",
    "essay",
    "topic",
    "proof",
    "paper",
    "tardy",
    "sheet",
    "guide",
    "grade",
    "boost",
    "brain",
    "extra",
    "sheet",
    "jocky",
  ],
  "6": [
    // "animal",
    // "banana",
    // "bubble",
    // "candle",
    // "income",
    // "wealth",
    // "profit",
    // "gentle",
    // "honest",
    // "humble",
    // "rescue",
    // "secure",
    // "kindly",
    // "warmth",
    // "budget",
    // "reward",
    // "credit",
    // "luxury",
    // "invest",
    // "status",
    // "circle",
    // "donkey",
    // "mentor",
    // "reward",
    // "growth",
    // "income",
    // "effort",
    // "active",
    // "wisdom",
    // "humble",
    // "honest",
    // "buffer",
    // "device",
    // "script",
    // "server",
    // "cookie",
    // "vector",
    // "router",
    // "binary",
    // "client",
    // "kernel",
    // "humble",
    // "joyful",
    // "caring",
    // "worthy",
    // "helper",
    // "giving",
    // "strong",
    // "polite",
    // "bright",
    // "family",
    // "garden",
    // "hammer",
    // "island",
    // "jungle",
    // "kitten",
    // "laptop",
    // "magnet",
    // "napkin",
    // "orange",
    // "pickle",
    // "quartz",
    // "rocket",
    // "tunnel",
    // "violin",
    // "window",
    // "yellow",
    // "zipper",
    // "anchor",
    // "bottle",
    // "crayon",
    // "drawer",
    // "engine",
    // "forest",
    // "goblin",
    // "helmet",
    // "insect",
    // "jacket",
    // "kitten",
    // "legend",
    // "market",
    // "nature",
    // "object",
    // "planet",
    // "quiver",
    // "ribbon",
    // "school",
    // "update",
    // "vacuum",
    // "whales",
    // "aboard",
    // "basket",
    // "cheese",
    // "dragon",
    // "excite",
    // "freeze",
    // "glider",
    // "honest",
    // "invite",
    // "juggle",
    // "karate",
    // "listen",
    // "marble",
    // "napkin",
    // "online",
    // "people",
    // "quaint",
    // "rescue",
    // "sprout",
    // "travel",
    // "unique",
    // "valley",
    // "wonder",
    // "energy",
    // "forest",
    // "galaxy",
    // "income",
    // "lesson",
    // "museum",
    // "winner",
    // "nature",
    // "object",
    // "rocket",
    // "silent",
    // "ticket",
    // "wander",
    // "cooked",
    // "locked",
    // "friend",
    // "blazin",
    "gentle",
    "bright",
    "friend",
    "caring",
    "glance",
    "shared",
    "silent",
    "earned",
    "shared",
    "joyful",
    "honest",
    "answer",
    "giving",
    "nature",
    "shared",
    "friend",
    "gentle",
    "system",
    "thanks",
    "friend",
    "steady",
    "intent",
    "friend",
    "shared",
    "secret",
    "gentle",
    "warmly",
    "tender",
    "shared",
    "burden",
    "mutual",
    "common",
    "ground",
    "family",
    "shared",
    "gentle",
    "relief",
    "friend",
    "shared",
    "steady",
    "warmth",
    "shared",
    "gentle",
    "binary",
    "server",
    "stream",
    "signal",
    "device",
    "editor",
    "system",
    "driver",
    "router",
    "config",
    "mobile",
    "domain",
    "switch",
    "stream",
    "device",
    "signal",
    "packet",
    "branch",
    "memory",
    "device",
    "output",
    "client",
    "filter",
    "syntax",
    "commit",
    "deploy",
    "script",
    "server",
    "uptime",
    "render",
    "design",
    "docker",
    "cookie",
    "crypto",
    "module",
    "static",
    "vision",
    "strong",
    "streak",
    "growth",
    "bright",
    "future",
    "effort",
    "effort",
    "vision",
    "steady",
    "vision",
    "hustle",
    "strong",
    "finish",
    "earned",
    "steady",
    "growth",
    "effort",
    "career",
    "action",
    "steady",
    "earned",
    "vision",
    "bright",
    "action",
    "timely",
    "career",
    "hustle",
    "pencil",
    "school",
    "report",
    "school",
    "lesson",
    "school",
    "school",
    "drawer",
    "school",
    "credit",
    "review",
    "review",
    "rubric",
    "snacks",
    "lesson",
    "rubric",
    "school",
    "school",
    "lounge",
    "lesson",
    "review",
  ],
  "7": [
    // "convert",
    // "empathy",
    // "problem",
    // "nurture",
    // "savings",
    // "curious",
    // "insight",
    // "helpful",
    // "forgive",
    // "respect",
    // "fortune",
    // "payment",
    // "support",
    // "respect",
    // "patient",
    // "comfort",
    // "healing",
    // "lovable",
    // "devoted",
    // "sincere",
    // "embrace",
    // "balance",
    // "earnest",
    // "deposit",
    // "premium",
    // "venture",
    // "success",
    // "resolve",
    // "patient",
    // "earnest",
    // "focused",
    // "network",
    // "mindset",
    // "support",
    // "control",
    // "network",
    // "monitor",
    // "browser",
    // "digital",
    // "compile",
    // "backend",
    // "gateway",
    // "printer",
    // "desktop",
    // "website",
    // "chicken",
    // "success",
    // "inspire",
    // "believe",
    // "hopeful",
    // "patient",
    // "support",
    // "mindful",
    // "balance",
    // "delight",
    // "climate",
    // "cookies",
    // "diamond",
    // "elastic",
    // "emerald",
    // "explore",
    // "factory",
    // "fortune",
    // "freedom",
    // "grammar",
    // "happily",
    // "harmony",
    // "imagine",
    // "impress",
    // "journey",
    // "landing",
    // "library",
    // "marbles",
    // "message",
    // "notepad",
    // "pattern",
    // "playful",
    // "pretend",
    // "printer",
    // "rejoice",
    // "respect",
    // "science",
    // "someone",
    // "sunrise",
    // "teacher",
    // "helpful",
    // "unicorn",
    // "village",
    // "webpage",
    // "silence",
    // "passive",
    "hopeful",
    "support",
    "respect",
    "gesture",
    "patient",
    "offered",
    "support",
    "sincere",
    "gesture",
    "forgive",
    "quickly",
    "empathy",
    "welcome",
    "comfort",
    "offered",
    "smiling",
    "offered",
    "support",
    "support",
    "healing",
    "feeling",
    "respect",
    "comfort",
    "support",
    "healing",
    "helpful",
    "gesture",
    "empathy",
    "trusted",
    "respect",
    "offered",
    "lasting",
    "healing",
    "support",
    "storage",
    "network",
    "browser",
    "command",
    "console",
    "backend",
    "version",
    "control",
    "session",
    "timeout",
    "tracker",
    "handler",
    "snippet",
    "package",
    "machine",
    "focused",
    "mindset",
    "reached",
    "picture",
    "forward",
    "project",
    "science",
    "college",
    "teacher",
    "history",
    "reading",
    "science",
    "subject",
    "reading",
    "project",
    "planner",
    "anxiety",
    "teacher",
    "library",
    "teacher",
  ],
  "8": [
    // "variable",
    // "solution",
    // "learning",
    // "abundant",
    // "security",
    // "treasure",
    // "currency",
    // "increase",
    // "interest",
    // "solution",
    // "positive",
    // "valuable",
    // "overcome",
    // "thoughts",
    // "resource",
    // "diligent",
    // "strength",
    // "inventor",
    // "decision",
    // "ambition",
    // "feedback",
    // "bathroom",
    // "kindness",
    // "kindness",
    // "computer",
    // "software",
    // "hardware",
    // "database",
    // "protocol",
    // "internet",
    // "terminal",
    // "security",
    // "positive",
    // "function",
    // "generous",
    // "creative",
    // "computer",
    // "cupcakes",
    // "daylight",
    // "dinosaur",
    // "goodness",
    // "grateful",
    // "handmade",
    // "homework",
    "pancakes",
    "password",
    "friendly",
    "neighbor",
    "grateful",
    "kindness",
    "returned",
    "reliable",
    "trusting",
    "offering",
    "welcomed",
    "listener",
    "cheerful",
    "internet",
    "protocol",
    "function",
    "security",
    "terminal",
    "keyboard",
    "shortcut",
    "conflict",
    "frontend",
    "viewport",
    "database",
    "firewall",
    "function",
    "terminal",
    "pipeline",
    "endpoint",
    "sequence",
    "decision",
    "achieved",
    "deadline",
    "learning",
    "question",
    "academic",
    "notebook",
    "notebook",
  ],
  "9": [
    "waterfall",
    "welcoming",
    "listening",
    "uplifting",
    "emotional",
    "framework",
    // "websocket",
    "clipboard",
    "promotion",
    "classmate",
    "sharpener",
    "worksheet",
    // "abundance",
    // "compassion",
    // "affection",
    // "forgiving",
    // "thoughtful",
    // "financial",
    // "inflation",
    // "gratitude",
    // "uplifting",
    // "classroom",
    // "discovery",
    // "gathering",
    // "happiness",
    // "storybook",
  ],
  // "10": [
  //   // "thoughtful",
  //   // "neighborly",
  //   // "compassion",
  //   // "friendship",
  //   // "javascript",
  //   // "validation",
  //   // "responsive",
  //   // "connection",
  //   // "worthwhile",
  // ],
};
