interface WordsByLength {
  [key: string]: string[];
}

// export const words: WordsByLength = {

//   "3": [
//     "study",
//     "time",
//     "test",
//     "day",
//     // "school",
//     // "supplies",
//     // "sharp",
//     // "pencil",
//     // "open",
//     // "book",
//     // "final",
//     // "exam",
//     // "brain",
//     // "power",
//     // "class",
//     // "project",
//     // "learning",
//     // "curve",
//     // "teachers",
//     // "desk",
//   ],
// };
export const words: WordsByLength = {
  "2": ["up", "in"],
  "3": [
    "hug",
    "joy",
    "ear",
    "you",
    "act",
    "usb",
    "api",
    "web",
    "gpu",
    "bit",
    "cpu",
    "app",
    "log",
    "tag",
    "css",
    "dns",
    "sql",
    "git",
    "dev",
    "ssl",
    "cli",
    "npm",
    "big",
    "win",
    "job",
    "run",
    "bar",
    "top",
    "key",
    "new",
    "met",
    "hit",
    "fix",
    "aim",
    "day",
    "lab",
    "pop",
    "pen",
    "ink",
    "aid",
    "due",
    "pad",
    "pet",
    "bus",

    "ant",
    "bat",
    "the",
    "cat",
    "dog",
    "egg",
    "fan",
    "gum",
    "hat",
    "ice",
    "jam",
    "kid",
    "log",
    "man",
    "net",
    "map",
    "owl",
    "pen",
    "rat",
    "sun",
    "tap",
    "urn",
    "van",
    "web",
    "yak",
    "zip",
    "bag",
    "cap",
    "den",
    "ear",
    "fig",
    "gap",
    "mid",
    "hop",
    "ink",
    "jet",
    "sus",
    "kit",
    "lid",
    "nap",
    "oak",
    "pit",
    "rib",
    "sip",
    "top",
    "urn",
    "vet",
    "win",
    "xen",
    "yam",
    "zen",
    "ace",
    "bee",
    "cub",
    "joy",
    "fun",
    "yes",
    "win",
    "sun",
    "gem",
    "hug",
    "dip",
    "elf",
    "fin",
    "got",
    "hen",
    "job",
    "key",
    "low",
    "mix",
    "nod",
    "off",
    "pop",
    "ran",
    "tin",
    "use",
    "vow",
    "box",
    "dot",
    "eat",
    "fix",
    "gym",
    "hug",
    "ion",
    "jar",
    "kin",
    "lay",
    "mom",
    "net",
    "old",
    "ask",
    "aid",
    "win",
    "try",
    "net",
    "tip",
    "joy",
    "pad",
    "run",
    "tag",
    "try",
    "upn",
    "wet",
    "yep",
    "zip",
    "ark",
    "bud",
    "cow",
    "app",
    "cpu",
    "ram",
    "api",
    "pay",
    "win",
    "net",
    "tip",
    "bag",
    "job",
    "gem",
    "gui",
    "usb",
    "web",
    "vpn",
    "mac",
    "ssd",
    "dig",
    "end",
    "was",
    "cap",
    "who",
  ],
  "4": [
    "help",
    "hand",
    "warm",
    "soft",
    "open",
    "arms",
    "eyes",
    "kind",
    "true",
    "talk",
    "safe",
    "calm",
    "soul",
    "wave",
    "deep",
    "love",
    "ally",
    "fair",
    "play",
    "grin",
    "good",
    "gift",
    "nice",
    "word",
    "kept",
    "bond",
    "made",
    "pure",
    "beam",
    "door",
    "care",
    "zone",
    "ears",
    "code",
    "data",
    "wifi",
    "port",
    "call",
    "node",
    "gate",
    "tool",
    "page",
    "boot",
    "rate",
    "ping",
    "test",
    "core",
    "disk",
    "miss",
    "tech",
    "name",
    "loop",
    "file",
    "path",
    "byte",
    "html",
    "grid",
    "sync",
    "base",
    "loss",
    "case",
    "leak",
    "spam",
    "repo",
    "form",
    "rule",
    "cert",
    "hash",
    "user",
    "auth",
    "push",
    "dark",
    "mode",
    "copy",
    "site",
    "goal",
    "plan",
    "move",
    "bold",
    "step",
    "hard",
    "work",
    "mind",
    "next",
    "firm",
    "will",
    "path",
    "long",
    "high",
    "task",
    "done",
    "well",
    "grit",
    "earn",
    "form",
    "haul",
    "team",
    "keep",
    "turn",
    "idea",
    "dive",
    "risk",
    "role",
    "pace",
    "wise",
    "gain",
    "list",
    "hope",
    "held",
    "mark",
    "peak",
    "game",
    "face",
    "fast",
    "lane",
    "lead",
    "beat",
    "paid",
    "quiz",
    "note",
    "card",
    "desk",
    "book",
    "exam",
    "coat",
    "math",
    "prep",
    "bell",
    "hour",
    "trip",
    "text",
    "time",
    "home",
    "roll",
    "dust",
    "term",
    "lamp",
    "peer",
    "ring",
    "hall",
    "read",
    "edge",
    "slip",
    "pass",
    "bird",
    "cake",
    "what",
    "when",
    "code",
    "drip",
    "data",
    "html",
    "java",
    "gold",
    "cash",
    "king",
    "coin",
    "save",
    "earn",
    "rich",
    "fund",
    "deal",
    "sale",
    "gain",
    "byte",
    "bash",
    "node",
    "disk",
    "file",
    "ping",
    "duck",
    "fish",
    "goat",
    "hand",
    "jump",
    "kite",
    "lamp",
    "moon",
    "nest",
    "open",
    "play",
    "rain",
    "ship",
    "tree",
    "kind",
    "good",
    "love",
    "hope",
    "nice",
    "fair",
    "hero",
    "glad",
    "calm",
    "free",
    "unit",
    "vent",
    "wind",
    "xray",
    "yarn",
    "zinc",
    "ball",
    "cold",
    "drum",
    "ever",
    "frog",
    "girl",
    "hill",
    "iron",
    "joke",
    "lava",
    "mice",
    "name",
    "oven",
    "peck",
    "quiz",
    "rock",
    "sand",
    "toes",
    "urge",
    "view",
    "wolf",
    "yard",
    "zoom",
    "ally",
    "bake",
    "calm",
    "dive",
    "echo",
    "farm",
    "game",
    "heat",
    "idea",
    "jade",
    "keep",
    "leaf",
    "mint",
    "love",
    "help",
    "care",
    "give",
    "kind",
    "calm",
    "soft",
    "safe",
    "true",
    "dear",
    "note",
    "oval",
    "pack",
    "race",
    "seat",
    "tide",
    "vast",
    "wave",
    "xmas",
    "zero",
    "arch",
    "belt",
    "clay",
    "deer",
    "each",
    "face",
    "gift",
    "hard",
    "inch",
    "join",
    "loud",
    "melt",
    "neck",
    "ogle",
    "pine",
    "rope",
    "song",
    "tent",
    "unit",
    "vase",
    "walk",
    "yoga",
    "zone",
    "aqua",
    "blue",
    "cool",
    "door",
    "kind",
    "help",
    "kind",
    "give",
    "earn",
    "self",
    "grow",
    "gain",
    "idea",
    "plan",
    "wise",
    "calm",
  ],
  "5": [
    "apple",
    "bunny",
    "chair",
    "learn",
    "slaps",
    "think",
    "solve",
    "heart",
    "peace",
    "share",
    "sweet",
    "trust",
    "grace",
    "angel",
    "touch",
    "grass",
    "smile",
    "human",
    "unity",
    "brave",
    "share",
    "trust",
    "skill",
    "grasp",
    "value",
    "asset",
    "bonus",
    "worth",
    "stock",
    "prize",
    "raise",
    "trade",
    "bucks",
    "trust",
    "value",
    "focus",
    "dance",
    "eagle",
    "flame",
    "happy",
    "smile",
    "peace",
    "trust",
    "brave",
    "shine",
    "input",
    "array",
    "block",
    "cloud",
    "mouse",
    "drive",
    "email",
    "logic",
    "fetch",
    "proxy",
    "cheer",
    "sweet",
    "thank",
    "charm",
    "grape",
    "house",
    "igloo",
    "jelly",
    "koala",
    "lemon",
    "magic",
    "nurse",
    "ocean",
    "piano",
    "queen",
    "robot",
    "smile",
    "tiger",
    "uncle",
    "vivid",
    "whale",
    "xylos",
    "yacht",
    "zebra",
    "angle",
    "baker",
    "candy",
    "daisy",
    "eager",
    "fairy",
    "giant",
    "happy",
    "index",
    "jolly",
    "kneel",
    "laugh",
    "match",
    "orbit",
    "plant",
    "quiet",
    "rainy",
    "shine",
    "train",
    "under",
    "vocal",
    "wrist",
    "yummy",
    "zippy",
    "acorn",
    "brave",
    "clean",
    "dream",
    "earth",
    "field",
    "glide",
    "heart",
    "inbox",
    "jumps",
    "liver",
    "merry",
    "noble",
    "organ",
    "pouch",
    "quack",
    "rider",
    "smart",
    "ultra",
    "voice",
    "world",
    "xenon",
    "youth",
    "azure",
    "beach",
    "cloud",
    "drill",
    "enter",
    "flock",
    "grill",
    "honey",
    "input",
    "jewel",
    "karma",
    "lemon",
    "mango",
    "night",
    "oasis",
    "penny",
    "quick",
    "river",
    "swing",
    "trick",
    "unity",
    "vapor",
    "witty",
    "zonal",
    "power",
    "eagle",
    "heart",
    "smile",
    "touch",
    "peace",
    "space",
    "sweet",
    "words",
    "voice",
    "trust",
    "brave",
    "cheer",
    "given",
    "shown",
    "laugh",
    "grace",
    "faith",
    "thank",
    "light",
    "loyal",
    "quiet",
    "happy",
    "tears",
    "moral",
    "vibes",
    "group",
    "stack",
    "cloud",
    "logic",
    "debug",
    "smart",
    "drive",
    "error",
    "cache",
    "patch",
    "boost",
    "trace",
    "query",
    "build",
    "input",
    "mouse",
    "click",
    "email",
    "merge",
    "route",
    "width",
    "media",
    "image",
    "table",
    "login",
    "shell",
    "param",
    "react",
    "redux",
    "store",
    "token",
    "clear",
    "daily",
    "grind",
    "small",
    "habit",
    "level",
    "sharp",
    "dream",
    "value",
    "added",
    "focus",
    "solid",
    "major",
    "great",
    "pitch",
    "ethic",
    "lucky",
    "break",
    "clean",
    "board",
    "climb",
    "quick",
    "going",
    "right",
    "skill",
    "worth",
    "fight",
    "final",
    "pivot",
    "adapt",
    "shift",
    "reach",
    "chain",
    "study",
    "guide",
    "score",
    "class",
    "rules",
    "lunch",
    "chalk",
    "grade",
    "field",
    "white",
    "paper",
    "notes",
    "pride",
    "honor",
    "chair",
    "brain",
    "storm",
    "sheet",
    "tutor",
    "extra",
    "scale",
    "essay",
    "topic",
    "proof",
    "tardy",
    "boost",
    "jocky",
  ],
  "6": [
    "animal",
    "banana",
    "bubble",
    "candle",
    "income",
    "wealth",
    "profit",
    "gentle",
    "honest",
    "humble",
    "rescue",
    "secure",
    "kindly",
    "warmth",
    "budget",
    "reward",
    "credit",
    "luxury",
    "invest",
    "status",
    "circle",
    "donkey",
    "mentor",
    "reward",
    "growth",
    "income",
    "effort",
    "active",
    "wisdom",
    "humble",
    "honest",
    "buffer",
    "device",
    "script",
    "server",
    "cookie",
    "vector",
    "router",
    "binary",
    "client",
    "kernel",
    "humble",
    "joyful",
    "caring",
    "worthy",
    "helper",
    "giving",
    "strong",
    "polite",
    "bright",
    "family",
    "garden",
    "hammer",
    "island",
    "jungle",
    "kitten",
    "laptop",
    "magnet",
    "napkin",
    "orange",
    "pickle",
    "quartz",
    "rocket",
    "tunnel",
    "violin",
    "window",
    "yellow",
    "zipper",
    "anchor",
    "bottle",
    "crayon",
    "drawer",
    "engine",
    "forest",
    "goblin",
    "helmet",
    "insect",
    "jacket",
    "kitten",
    "legend",
    "market",
    "nature",
    "object",
    "planet",
    "quiver",
    "ribbon",
    "school",
    "update",
    "vacuum",
    "whales",
    "aboard",
    "basket",
    "cheese",
    "dragon",
    "excite",
    "freeze",
    "glider",
    "honest",
    "invite",
    "juggle",
    "karate",
    "listen",
    "marble",
    "napkin",
    "online",
    "people",
    "quaint",
    "rescue",
    "sprout",
    "travel",
    "unique",
    "valley",
    "wonder",
    "energy",
    "forest",
    "galaxy",
    "income",
    "lesson",
    "museum",
    "winner",
    "nature",
    "object",
    "rocket",
    "silent",
    "ticket",
    "wander",
    "cooked",
    "locked",
    "friend",
    "blazin",
    "gentle",
    "bright",
    "friend",
    "caring",
    "glance",
    "shared",
    "silent",
    "earned",
    "joyful",
    "honest",
    "answer",
    "giving",
    "nature",
    "system",
    "thanks",
    "steady",
    "intent",
    "secret",
    "warmly",
    "tender",
    "burden",
    "mutual",
    "common",
    "ground",
    "family",
    "relief",
    "warmth",
    "binary",
    "server",
    "stream",
    "signal",
    "device",
    "editor",
    "driver",
    "router",
    "config",
    "mobile",
    "domain",
    "switch",
    "packet",
    "branch",
    "memory",
    "output",
    "client",
    "filter",
    "syntax",
    "commit",
    "deploy",
    "script",
    "uptime",
    "render",
    "design",
    "docker",
    "cookie",
    "crypto",
    "module",
    "static",
    "vision",
    "strong",
    "streak",
    "growth",
    "future",
    "effort",
    "hustle",
    "finish",
    "career",
    "action",
    "timely",
    "pencil",
    "school",
    "report",
    "lesson",
    "drawer",
    "credit",
    "review",
    "rubric",
    "snacks",
    "lounge",
  ],
  "7": [
    "convert",
    "empathy",
    "problem",
    "nurture",
    "savings",
    "curious",
    "insight",
    "helpful",
    "forgive",
    "respect",
    "fortune",
    "payment",
    "support",
    "respect",
    "patient",
    "comfort",
    "healing",
    "lovable",
    "devoted",
    "sincere",
    "embrace",
    "balance",
    "earnest",
    "deposit",
    "premium",
    "venture",
    "success",
    "resolve",
    "patient",
    "earnest",
    "focused",
    "network",
    "mindset",
    "support",
    "control",
    "network",
    "monitor",
    "browser",
    "digital",
    "compile",
    "backend",
    "gateway",
    "printer",
    "desktop",
    "website",
    "chicken",
    "success",
    "inspire",
    "believe",
    "hopeful",
    "patient",
    "support",
    "mindful",
    "balance",
    "delight",
    "climate",
    "cookies",
    "diamond",
    "elastic",
    "emerald",
    "explore",
    "factory",
    "fortune",
    "freedom",
    "grammar",
    "happily",
    "harmony",
    "imagine",
    "impress",
    "journey",
    "landing",
    "library",
    "marbles",
    "message",
    "notepad",
    "pattern",
    "playful",
    "pretend",
    "printer",
    "rejoice",
    "respect",
    "science",
    "someone",
    "sunrise",
    "teacher",
    "helpful",
    "unicorn",
    "village",
    "webpage",
    "silence",
    "passive",
    "hopeful",
    "support",
    "respect",
    "gesture",
    "patient",
    "offered",
    "sincere",
    "forgive",
    "quickly",
    "empathy",
    "welcome",
    "comfort",
    "smiling",
    "healing",
    "feeling",
    "helpful",
    "trusted",
    "lasting",
    "storage",
    "network",
    "browser",
    "command",
    "console",
    "backend",
    "version",
    "control",
    "session",
    "timeout",
    "tracker",
    "handler",
    "snippet",
    "package",
    "machine",
    "focused",
    "mindset",
    "reached",
    "picture",
    "forward",
    "project",
    "science",
    "college",
    "teacher",
    "history",
    "reading",
    "subject",
    "planner",
    "anxiety",
    "library",
  ],
  "8": [
    "variable",
    "solution",
    "learning",
    "abundant",
    "security",
    "treasure",
    "currency",
    "increase",
    "interest",
    "solution",
    "positive",
    "valuable",
    "overcome",
    "thoughts",
    "resource",
    "diligent",
    "strength",
    "inventor",
    "decision",
    "ambition",
    "feedback",
    "bathroom",
    "kindness",
    "kindness",
    "computer",
    "software",
    "hardware",
    "database",
    "protocol",
    "internet",
    "terminal",
    "security",
    "positive",
    "function",
    "generous",
    "creative",
    "computer",
    "cupcakes",
    "daylight",
    "dinosaur",
    "goodness",
    "grateful",
    "handmade",
    "homework",
    "pancakes",
    "password",
    "friendly",
    "neighbor",
    "grateful",
    "kindness",
    "returned",
    "reliable",
    "trusting",
    "offering",
    "welcomed",
    "listener",
    "cheerful",
    "internet",
    "protocol",
    "function",
    "security",
    "terminal",
    "keyboard",
    "shortcut",
    "conflict",
    "frontend",
    "viewport",
    "database",
    "firewall",
    "pipeline",
    "endpoint",
    "sequence",
    "decision",
    "achieved",
    "deadline",
    "learning",
    "question",
    "academic",
    "notebook",
  ],
  "9": [
    "waterfall",
    "welcoming",
    "listening",
    "uplifting",
    "emotional",
    "framework",
    // "websocket",
    "clipboard",
    "promotion",
    "classmate",
    "sharpener",
    "worksheet",
    // "abundance",
    // "compassion",
    // "affection",
    // "forgiving",
    // "thoughtful",
    // "financial",
    // "inflation",
    // "gratitude",
    // "uplifting",
    // "classroom",
    // "discovery",
    // "gathering",
    // "happiness",
    // "storybook",
  ],
  // "10": [
  //   // "thoughtful",
  //   // "neighborly",
  //   // "compassion",
  //   // "friendship",
  //   // "javascript",
  //   // "validation",
  //   // "responsive",
  //   // "connection",
  //   // "worthwhile",
  // ],
  items: ["diamond", "ruby", "emerald", "sapphire", "gold"],
  powerups: ["end", "time", "life"],
};

export const collectiblePairs = {
  Social: [
    "kind heart",
    "help hand",
    "warm hug",
    "soft smile",
    "open arms",
    "gentle touch",
    "bright eyes",
    "true friend",
    "peace talk",
    "safe space",
    "sweet words",
    "calm voice",
    "caring soul",
    "friendly wave",
    "hopeful glance",
    "shared joy",
    "silent support",
    "trust earned",
    // "deep compassion",
    "love shared",
    "brave ally",
    "cheer given",
    "fair play",
    "joyful hug",
    "honest answer",
    "respect shown",
    "welcoming grin",
    "good neighbor",
    "grateful heart",
    // "thoughtful gift",
    "nice gesture",
    "giving nature",
    "kindness returned",
    "shared laugh",
    "listening ear",
    "patient friend",
    "gentle word",
    "grace offered",
    "support system",
    "faith kept",
    "bond made",
    "sincere thanks",
    "sweet gesture",
    "forgive quickly",
    "soft heart",
    "true smile",
    "thank you",
    "empathy given",
    "warm welcome",
    "comfort offered",
    "uplifting word",
    "smiling eyes",
    "reliable friend",
    // "neighborly wave",
    "steady hand",
    "light touch",
    "open heart",
    "pure intent",
    "compassion offered",
    "loyal friend",
    "trusting bond",
    "support beam",
    "shared secret",
    "peace offering",
    "emotional support",
    "healing hug",
    "gentle eyes",
    "safe feeling",
    "welcomed warmly",
    "open door",
    "quiet listener",
    "tender care",
    "shared burden",
    "mutual respect",
    "common ground",
    "family bond",
    "happy tears",
    "laugh shared",
    "comfort zone",
    "moral support",
    "healing space",
    "helpful hand",
    "kind act",
    "gentle gesture",
    "relief given",
    "true empathy",
    "good vibes",
    "group hug",
    "trusted friend",
    "shared love",
    "respect offered",
    // "lasting friendship",
    "peace made",
    "open ears",
    "steady smile",
    "cheerful grin",
    "healing words",
    "support given",
    "warmth shared",
    "gentle help",
  ],
  Technology: [
    "binary code",
    "server stack",
    "data stream",
    "cloud storage",
    "wifi signal",
    "usb port",
    "api call",
    "network node",
    "logic gate",
    "debug tool",
    "smart device",
    "web page",
    "code editor",
    "system boot",
    "drive error",
    "gpu driver",
    "bit rate",
    "ping test",
    "cpu core",
    "disk space",
    "cache miss",
    "router config",
    "mobile app",
    "tech stack",
    "internet browser",
    "domain name",
    "protocol switch",
    // "javascript loop",
    "file path",
    "loop function",
    "error log",
    "byte stream",
    "logic error",
    "html tag",
    "css grid",
    "security patch",
    "device sync",
    "signal boost",
    "code base",
    "stack trace",
    "packet loss",
    "dns query",
    "code branch",
    "test case",
    "build error",
    "terminal command",
    "debug console",
    "sql query",
    "memory leak",
    "input device",
    "output port",
    "mouse click",
    "keyboard shortcut",
    "email client",
    "spam filter",
    "syntax error",
    "git repo",
    "merge conflict",
    "commit log",
    "deploy script",
    "server uptime",
    "dev tool",
    "frontend framework",
    "backend route",
    // "form validation",
    "render loop",
    "viewport width",
    "media query",
    // "responsive design",
    "docker image",
    "version control",
    "database table",
    "login form",
    "session timeout",
    "cookie tracker",
    "firewall rule",
    "ssl cert",
    "crypto hash",
    "function call",
    // "websocket connection",
    "user auth",
    "error handler",
    "dark mode",
    "code snippet",
    "clipboard copy",
    "cli tool",
    "terminal shell",
    "dev mode",
    "build pipeline",
    "query param",
    "api endpoint",
    "node module",
    "npm package",
    "react hook",
    "redux store",
    "token auth",
    "machine code",
    "boot sequence",
    "static site",
    "landing page",
  ],
  Success: [
    "big goal",
    "clear plan",
    "daily grind",
    "small win",
    "smart move",
    "bold step",
    "hard work",
    "focused mind",
    "good habit",
    "next level",
    "sharp vision",
    "firm decision",
    "strong will",
    "goal achieved",
    "win streak",
    "dream job",
    "clear path",
    "long run",
    "high bar",
    "growth mindset",
    "task done",
    "grit shown",
    "value added",
    "earn trust",
    "well done",
    "bright future",
    "deep focus",
    "solid plan",
    "true grit",
    // "worthwhile effort",
    "top form",
    "goal reached",
    "sharp mind",
    "effort shown",
    "key step",
    "major win",
    "long haul",
    "level up",
    "great pitch",
    "work ethic",
    "lucky break",
    "clean win",
    "firm goal",
    "big picture",
    "vision board",
    "grind mode",
    "steady climb",
    "team win",
    "quick win",
    "bold vision",
    "daily hustle",
    "keep going",
    "push forward",
    "strong finish",
    "sharp turn",
    "right move",
    "big idea",
    "deep dive",
    "new skill",
    "value earned",
    "worth fight",
    "steady growth",
    "right call",
    "final push",
    "team effort",
    "career move",
    "action plan",
    "next step",
    "smart risk",
    "new role",
    "steady pace",
    "quick pivot",
    "goal met",
    "deadline hit",
    "promotion earned",
    "plan made",
    "vision clear",
    "wise move",
    "bright path",
    "calm mind",
    "bold action",
    "quick adapt",
    "timely fix",
    "major shift",
    "level gain",
    "dream reach",
    "small step",
    "goal list",
    "hope held",
    "top mark",
    "peak form",
    "game face",
    "win goal",
    "fast lane",
    "career climb",
    "lead role",
    "goal chain",
    "task beat",
    "hustle paid",
    "aim true",
    "chicken jocky",
    "locked in",
  ],
  Academia: [
    "study guide",
    "test day",
    "quiz score",
    "pencil case",
    "note card",
    "school desk",
    "open book",
    "sharp mind",
    "final exam",
    "lab coat",
    "class rules",
    "group project",
    "book report",
    "math test",
    "lunch break",
    "pop quiz",
    "science lab",
    "chalk board",
    "pen ink",
    "college prep",
    "grade level",
    "school bell",
    "study hour",
    "field trip",
    "lesson plan",
    "white board",
    "text book",
    "quiz time",
    "classmate help",
    "teacher aid",
    "paper due",
    "home work",
    "class note",
    "book stack",
    "math quiz",
    "history test",
    "reading log",
    "word list",
    "science fair",
    "quiz grade",
    "test prep",
    "open notes",
    "school pride",
    "honor roll",
    "desk chair",
    "subject guide",
    "brain storm",
    "chalk dust",
    "lab sheet",
    "school zone",
    "field notes",
    "desk drawer",
    "tutor help",
    "term paper",
    "reading lamp",
    "quiz board",
    "note pad",
    "math notes",
    "school play",
    "extra credit",
    "study tool",
    "exam review",
    "peer review",
    "project rubric",
    "final grade",
    "bell ring",
    "study break",
    "daily planner",
    "grade scale",
    "exam hall",
    "study snacks",
    "learning aid",
    "class pet",
    "test anxiety",
    "quiz app",
    "lesson test",
    "extra help",
    "group study",
    "exam question",
    "rubric score",
    "essay topic",
    "proof read",
    "school bus",
    "academic goal",
    "notebook paper",
    "sharpener edge",
    "tardy slip",
    "school trip",
    "teacher lounge",
    "library pass",
    "lab notebook",
    "quiz sheet",
    "home pass",
    "lesson guide",
    "grade boost",
    "brain work",
    "exam desk",
    "teacher note",
    "extra worksheet",
    "review sheet",
  ],
};

export const leagueTrophies = {
  bronze: { emoji: "🥉", color: "#cd7f32" },
  silver: { emoji: "🥈", color: "#c0c0c0" },
  gold: { emoji: "🥇", color: "#ffd700" },
  platinum: { emoji: "🌟", color: "#e5e4e2" }, // or pick a custom
};
